spring:
  config:
    import: classpath:env.properties
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 1000

stt:
  worker:
    base-url: http://localhost:8081   # 기본값/ 배포할때 EC2/Lambda 주소로 바꾸면 됨

app:
  s3:
    bucket: your-audio-bucket         # S3 이름/ 실제 배포할때 .env나 AWS Secrets Manager로 주입